### ISSUE TITLE
一个月后再更新，带娃一段时间

### ISSUE THREAD

**Issue by Faslyling** [weg2020/apkide#13]

**Comment by petermorrys** [comment]
Hello please faslyling I will like to get the complete source code of this to learn from it

**Comment by petermorrys** [comment]
you got only one repo in github and also   where can i chat you up if you
are on telegram or watsappp please send Link so that we can connect.
Thanks

**Comment by Faslyling** [comment]
> Hello please faslyling I will like to get the complete source code of this to learn from it

I'm sorry, I'm out of town, I don't have a computer with me, and I have to wait for a month

**Comment by petermorrys** [comment]
I am in cause I was giving a project in my school and which is related to
this your project it will be submitted this week Thursday so if there is
any link you can give me on where you get the project or send it from your
phone I will be greatfull    thanks
